{% set name = "itk-napari-conversion" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/itk_napari_conversion-{{ version }}.tar.gz
  sha256: 38bed0248dd8800f89a07029e72691c935cb42f3cc7aa9c2a17271ff3970c6ed

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - hatchling
    - pip
    - python {{ python_min }}
  run:
    - itk >=5.2.0
    - napari
    - python >={{ python_min }}

test:
  imports:
    - itk_napari_conversion
  commands:
    - pip list
    # - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/InsightSoftwareConsortium/itk-napari-conversion
  summary: Convert between itk and napari data structures.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - thewtex
